name: Compile LaTeX Document

on:
  push:
    branches:
      - report  # Change to the branch you want to trigger the workflow

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Churninator
      uses: actions/checkout@v4

    - name: Compile LaTeX document
      uses: dante-ev/latex-action@latest
      with:
        root_file: report/report.tex  # Replace with your main .tex file
        working_directory: report

