name: Compile LaTeX Document

on:
  push:
    branches:
      - report  # Change to the branch you want to trigger the workflow

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up LaTeX environment
      uses: dante-ev/latex-action@v2
      with:
        root_file: report.tex  # Replace with your main .tex file
        working_directory: /report

    - name: Upload compiled PDF
      uses: actions/upload-artifact@v2
      with:
        name: compiled-document
        path: report.pdf  # The output PDF file

